---
title: "5 - La correction des effets de calendrier"
subtitle: "Désaisonnalisation avec JDemetra+ et RJDemetra"
author: "Alain Quartier-la-Tente"
division: "Lemna, Insee"
departement: ""
logo: "img/logo"
output: 
    bookdown::beamer_presentation2:
        template: template.tex
        keep_tex: false
        theme: TorinoTh
        slide_level: 3
        fig_caption: true
themeoptions: "coding=utf8,language=french"
classoption: 'usepdftitle=false,french'
fontsize: 10pt
lan: french
---

```{r setup, include=FALSE}
options(xtable.comment = FALSE)
library(ggplot2)
library(reshape2)
beamer_textwidth <- 11.13435
beamer_textheight <- 7.89807
conv_cm_to_in <- 0.393701
conv_cm_to_px <- 75
knitr::opts_chunk$set(echo = FALSE, fig.pos = 'H',message=FALSE,
                      fig.height = beamer_textheight * conv_cm_to_in,
                      fig.width =  beamer_textwidth * conv_cm_to_in)
```

### Objectifs de cette séquence
Cette séquence a pour objectifs de vous présenter les différents effets de calendrier et la manière de corriger une série de ces effets  

Après cette séquence vous saurez :  

- Les différents effets de calendrier  

- Les raisons pour lesquelles il est utile de corriger une série de ces effets  

- La manière de corriger une série de ces effets  

- Les diagnostics disponibles sous JDemetra+ permettant de s'assurer que la série CVS-CJO ne présente pas d'effets de calendrier résiduels


### Questions de positionnement

Pourquoi corriger des effets de calendrier ?
\vfill

Quels sont les 3 effets du calendrier ?
\vfill

Pourquoi il est utile de désaisonnaliser les régresseurs du calendrier ?
\vfill

La correction des effets de calendriers dépend de quel type d'hypothèses ?
\vfill

Que faut-il vérifier pour valider la correction des effets de calendriers ?
\vfill

# Pourquoi corriger des effets de calendrier ?

## Un calendrier hétérogène
### Un calendrier hétérogène

Le calendrier est hétérogène :  

- Les jours ouvrables :   
    + jours normalement travaillés compte tenu des habitudes de l'entreprise, le plus souvent, il s'agit des lundis, mardis,…, vendredis non fériés  

- Les week-ends  

- Les jours fériés (fêtes)  

Or tous les mois n'ont pas la même composition :  
$\implies$ Tous les mois ne sont pas « égaux » entre eux : on parle  d'**effets de calendrier**


## Les différents effets de calendrier
### Effet longueur du mois/trimestre

L'effet « année bissextile » (*leap year*)

Exemples :  

- La production est en principe plus élevée au cours d'un mois comportant davantage de jours ouvrables  
- Pour la France : nombre de jours ouvrables (lundis, mardis,…, vendredis non fériés) par trimestre :

\begin{table}[htbp]
  \centering
    \begin{tabular}{|c|c|c|c|c|}
    \hline
    Année & T1    & T2    & T3    & T4 \\
    \hline
    2010  & 63    & 62    & 65    & 64 \\
    \hline
    2011  & 64    & 62    & 64    & 63 \\
    \hline
    2012  & 65    & 60    & 64    & 64 \\
    \hline
    2013  & 63    & 60    & 65    & 63 \\
    \hline
    2014  & 63    & 60    & 64    & 64 \\
    \hline
    2015  & 63    & 60    & 65    & 64 \\
    \hline
    \textbf{Moyenne} & \textbf{63,50} & \textbf{60,67} & \textbf{64,50} & \textbf{63,67} \\
    \hline
    \end{tabular}
\end{table}


### Effet type de jour

Exemples :  

- Les ventes du commerce de détail sont plus importantes le samedi que les autres jours de la semaine

- Pour la France : nombre moyen de jours par type par trimestre entre 1940 et 2020 
\begin{table}[htbp]
  \centering \footnotesize
    \begin{tabular}{|l|c|c|c|c|}
    \hline
    Jours non fériés & T1    & T2    & T3    & T4 \\
    \hline
  Lundi & 12,89 & 13,00 & 13,15 & 13,15\\
  \hline
  Mardi & 12,89 & 13,00 & 13,15 & 13,15\\
  \hline
  Mercredi & 12,89 & 13,00 & 13,14 & 13,15\\
  \hline
  Jeudi & 12,90 & 13,00 & 13,14 & 13,14\\
  \hline
  Vendredi & 12,90 & 13,00 & 13,14 & 13,14\\
  \hline
  Samedi & 12,90 & 13,00 & 13,14 & 13,14\\
  \hline
  Dimanche & 12,89 & 13,00 & 13,15 & 13,14\\
    \hline \hline
    \hline
    Jours fériés & T1    & T2    & T3    & T4 \\
    \hline
    Lundi à vendredi & 0,91 & 3,26 & 1,43 & 1,43\\
    \hline
    Samedi & 0,14 & 0,28 & 0,29 & 0,29\\
    \hline
    Dimanche & -1,05 & -3,54 & -1,71 & -1,71\\
    \hline
    \end{tabular}
\end{table}

### Effets des jours fériés
\begin{table}[htbp]
\small
  \centering
    \begin{tabular}{|m{2.6cm}|>{\centering\arraybackslash} m{1.3cm}|m{9.145em}|m{7.285em}|}
    \hline
    \multicolumn{2}{|m{3.9cm}|}{Types de jours fériés } & Exemples & Effets \\
    \hline
    \multirow{2}{*}{Fête mobile} & Hors Pâques &  -- Lundi de Pentecôte\newline{} -- Jeudi de  l'Ascension\newline{} -- Lundi de Pâques\newline{} & Type de jours  \\
 \hhline{|~---|}     & Pâques  & {\cellcolor[rgb]{ .753,  .753,  .753}} & Effet graduel \\
    \hline
    \multicolumn{2}{|m{3.9cm}|}{Date fixe : ces jours fériés tombent toujours le même mois mais pas forcément le même jour de la semaine } & 01/01, 01/05, 08/05, 14/07, 15/08, 01/11, 11/11, 25/12  & Type de jours  \\
    \hline
    \end{tabular}
\end{table}

### L'effet graduel de Pâques

Pour certaines séries les variations liées à Pâques peuvent s'observer pendant les jours ou les semaines qui précèdent la fête : c'est ce qu'on appelle *effet graduel de Pâques*

Exemple : les ventes de fleurs et de chocolats augmentent sensiblement à l'approche de Pâques


\faArrowCircleRight{} a priori ce n'est pas le cas vos séries, dans RJDemetra utiliser l'option `easter.enabled = FALSE`.


## Corriger pour comparer

### Corriger pour comparer

Il est nécessaire de corriger des effets de calendrier pour pouvoir faire :  

- Des comparaisons temporelles   
    + Exemple : mois de longueurs différentes  
    
- Des comparaisons sectorielles (i.e. entre différents secteurs d'activité)  
    + Exemple : le commerce et l'industrie (effet « type de jours »)  
    
- Des comparaisons spatiales (exemple : entre différents pays)  
    + Exemple : la France et l'Allemagne n'ont pas le même nombre de jours ouvrables par mois  
        * Jours fériés différents  
        * Religions différentes (calendrier orthodoxe vs calendrier chrétien)


# Comment corriger des effets de calendrier ?

## De la saisonnalité dans le calendrier

### Effet calendrier en partie saisonnier

Une part des effets de calendrier est saisonnière :  

- Le nombre de jours ouvrables du mois de février est presque toujours inférieur à celui du mois de mars  

- Certains mois comptent plus de jours fériés (et donc moins de jours ouvrables) que les autres mois  
    + Exemple : le mois de mai en France  
    
$\implies$ Une part des effets de calendrier est prise en compte dans la correction des variations saisonnières



### Approche économétrique retenue

Hypothèse : l'effet de la longueur du mois (ou du trimestre) ou d'un certain type de jours de la semaine est constant sur toute la période d'étude

On va construire des jeux de régresseurs « effets de calendrier » désaisonnalisés et pertinents d'un point de vue économique en faisant des hypothèses sur les effets des différents types de jours :  

- Lundis non fériés  
- Mardis non fériés  
- …  
- Dimanches non fériés  
- Lundis fériés  
- Mardis fériés  
- …  
- Dimanches fériés  

Quelles sont, selon vous, les hypothèses les plus naturelles ?


### Modèle de base (hors jours fériés)

$$X_t = \sum_{i=1}^{7} \alpha_i N_{it} + \varepsilon_t$$

- $N_{it}$ est le nombre de jours de lundis ($i=1$), ..., dimanches ($i=7$)

- $\alpha_i$ effet d'un jour de type $i$

\faArrowCircleRight{} problème de colinéarité, on réécrit le modèle et on "désaisonnalise" les effets de calendrier :

$$X_t =  \sum_{i=1}^{6} \beta_i (N_{it} - N_{7t}) + \bar{\alpha} (N_t - \bar{N}_t) +  \varepsilon_t$$

Avec : $N_t = \sum_{i=1}^7 N_{it}$

- $\bar{\alpha} = \frac{1}{7} \sum_{i=1}^{7} \alpha_i$ = effet moyen d'un jour quelconque

- $\beta_i = \alpha_i - \bar{\alpha}$ = effet spécifique d'un jour de type $i$


## Les différents jeux de régresseurs 

### Exemples de jeux de régresseurs

\begin{table}[htbp]
  \centering\scriptsize
    \begin{tabular}{|m{0.1\textwidth}|m{0.44\textwidth}|m{0.2\textwidth}|>{\centering}m{0.12\textwidth}|}
    \hline
    Jeu de régresseurs & Hypothèses & Référence (contraste) & Nombre de régresseurs\tabularnewline
        \hline
    REG1 & (lundi non férié = \dots = vendredi non férié) et (Samedi = dimanche = jours fériés)  & Samedis, dimanches et jours fériés & 1 + LPY \tabularnewline
          \hline
    REG2 & (lundi non férié = \dots = vendredi non férié), (Samedi) et (Dimanche = jours fériés)  & Dimanches et jours fériés & 2 + LPY \tabularnewline
          \hline
    REG3 & (lundi non férié), (mardi non férié = \dots = vendredi non férié) et (Samedi = dimanche = jours fériés)  & Samedis, dimanches et jours fériés & 3 + LPY \tabularnewline
          \hline
    REG5 & (lundi non férié), \dots, (vendredi non férié) et (Samedi = dimanche = jours fériés)  & Samedis, dimanches et jours fériés & 5 + LPY \tabularnewline
          \hline
    REG6 & (lundi non férié), \dots, (vendredi non férié), (Samedi) et (Dimanche = jours fériés)  & Dimanches et jours fériés & 6 + LPY \tabularnewline
          \hline
    Leap Year (LPY) & Tous les jours ont le même effet & Tous les jours & 1 \tabularnewline
    \hline
    \end{tabular}
\end{table}

Dans JDemetra+, REG1 = *working days* et REG6 = *trading-days*.

\bcinfo Package [`rjd3modelling`](https://github.com/palatej/rjd3modelling) permet de générer tous les types de jeux de régresseurs.

## Une correction a priori de l'effet année bissextile

### Une correction a priori de l'effet année bissextile

\cite{B1992} suggère deux méthodes pour corriger de l'effet longueur du mois :

1. Ajouter un régresseur LY

2. Faire une correction *a priori* de la longueur du mois. Par exemple, `transform.adjust = "LeapYear"` équivaut à multiplier la série brute par $\alpha_{t} = \left\{ \begin{array}{rl} 
                \frac{28,25}{29} & \mbox{si } t \mbox{ est un mois de février bissextil } \\
                \frac{28,25}{28} & \mbox{si } t \mbox{ est un mois de février non bissextil } \\
                1 & \mbox{sinon}
               \end{array}
         \right.$

Les deux méthodes sont équivalentes si l'on a un modèle **multiplicatif** et coefficients estimé proche de 0,035 (ce qui est souvent le cas)


## Comment choisir et valider le choix du jeu de régresseurs ?

### Se poser les bonnes questions

Avant de choisir entre un jeu de régresseurs, il faut se poser les questions suivantes :  

- Est-ce que ma série peut présenter des effets de calendrier (sens économique) ?  

- Quels jours ont a priori un effet sur les valeurs de ma série ?  

    + Les jours non fériés du lundi au samedi ?  
    + Les jours non fériés du lundi au vendredi ?  
    + Tous les jours non fériés ont-ils a priori le même effet sur les valeurs de ma série ?

### Valider le choix réalisé

Après avoir choisi un des jeux de régresseurs, peut-on enlever un des régresseurs ?  

- la variable « Leap Year » ?  
    + Effet « longueur du mois » = 0  

- un des autres régresseurs ?  
    + Effet « type de jours » = 0 pour le régresseur enlevé  


# Les outils disponibles sous JDemetra+ 

## Les régresseurs de JDemetra+

### Les outils disponibles sous JDemetra+ et RJDemetra

JDemetra+ et RJDemetra proposent 2 jeux de régresseurs :  

- Trading Days (6 régresseurs)  
    + On distingue tous les jours de la semaine du lundi au samedi  
    
- Working Days (1 régresseur)  
    + On distingue les jours de la semaine (lundi = mardi = … = vendredi) et les week-ends  

- Leap year (1 régresseur ou corrigé avant la CJO)

On peut également utiliser ses propres jeux de régresseurs

## Tests de significativité des coefficients

### Deux tests disponibles

Dans les diagnostics (« Pre-processing »), JD+ fournit des tests de significativité portant sur le jeu de régresseurs choisi par l'utilisateur :

- Test de Fisher de nullité conjointe des coefficients ($H_0$ tous les coefficients sont nuls et $H_1$ au moins un des coefficients n'est pas nul)  
    + Peut conduire à enlever le jeu de régresseurs du modèle Reg-ARIMA  

- Pour chaque régresseur, test de Student de nullité du coefficient ($H_0$ le coefficient est nul et $H_1$ le coefficient n'est pas nul)  
    + Peut conduire à changer de jeu de régresseurs


## Test de l'effet graduel de Pâques

### Présence d'un effet graduel de Pâques ?
Est-ce que ma série peut présenter un effet graduel de Pâques ? 

- Si oui, j'introduis un régresseur permettant de corriger ma série de l'effet graduel 
    + Variable « Easter » dans JDemetra+  
    
- Si non, je n'en introduis pas  

- Si je ne sais pas, je peux demander à JDemetra+ de faire un test pour m'aider à décider
    + JDemetra+ peut réaliser un « pré-test » afin de savoir si la série présente un effet graduel de Pâques. Si c'est le cas, JD+ introduit le régresseur « Easter [n] » (n=1,…, 20) dans le modèle

Dans les diagnostics (« Pre-processing »), JDemetra+ fournit un test de la significativité du coefficient associé au régresseur « Easter [n] » (test de Student : $H_0$ coeff(Easter [n]) = 0 et $H_1$ coeff(Easter [n]) $\ne$ 0)

# Vérifier la qualité de la CJO

## Sur la qualité du modèle Reg-ARIMA

###

- Test de fisher de nullité des coefficients (package `car` sous R) ou test de student pour voir si on peut simplifier le modèle

- Tests spectraux : moins puissants

- Le changement du jeu de régresseur peu avoir un impact sur :

  - le modèle ARIMA
  
  - l'autocorrélation, l'hétéroscédasticité et la normalité
  
## Sur la désaisonnalisation

### Tests d'effets calendaires résiduels (1/2)

Tests les plus importants ! Effectués sur la série désaisonnalisée (`sa`) et sur l'irrégulier (`i`).

\bcattention Test effectué sur les 8 dernières années sous JDemetra+ et ensemble série sous RJDemetra !

\bcinfo Sous JDemetra+, pour changer les paramètres : Tools > option > Statistics > Diagnostics > residual trading days diagnostics 

\bcinfo Tests reproductibles avec `rjd3sa::td.f`. Trois modélisations possibles, $(H_0):\beta_1=\dots = \beta_6=0$ :

1. Par défaut sous JDemetra+ et `model = "AR"` sous `rjd3sa`
$$
y_t=c + \alpha y_{t-1} + \sum_{i=1}^{6} \beta_i (N_{it} - N_{7t}) +  \varepsilon_t
$$

### Tests d'effets calendaires résiduels (2/2)

2. `model = "D1"` 
$$
\Delta y_t - \overline{\Delta y}  =\sum_{i=1}^{6} \beta_i (N_{it} - N_{7t}) +  \varepsilon_t
$$

3. `model = "WN"`
$$
y_t - \bar y =\sum_{i=1}^{6} \beta_i (N_{it} - N_{7t}) +  \varepsilon_t
$$

avec $y_t=sa_t$ ou $y_t=i_t$ si le modèle est additif, $y_t=\log(sa_t)$ ou $y_t=\log(i_t)$ si le modèle est additif.

\bcattention il ne s'agit pas des composantes finales mais issues de X-11 !

# Conclusion

## Les essentiels 

### Les essentiels

- La correction des effets de calendrier est nécessaire pour faire des comparaisons temporelles et spatiales

- On distingue 3 différents effets : effet « longueur du mois » , effet « type de jours » et effet « fêtes mobiles » (Pâques)  

- On élabore ses propres jeux de régresseurs en faisant des hypothèses sur la similitude des types de jours

- Il faut s'assurer de l'absence d'effets de calendrier résiduels  


## Bibliographie

### Bibliographie  {.noframenumbering}

\footnotesize

\begin{thebibliography}{999}
\bibitem[Données désaisonnalisées FAQ]{FAQ} Données désaisonnalisées — Foire aux questions, Statistique Canada. \url{https://www150.statcan.gc.ca/n1/dai-quo/btd-add/btd-add-fra.htm}
\bibitem[Attal-Toubert (2012)]{A2012} Attal-Toubert, K. (2012), Régresseurs pour effets de calendrier : comment les construire, comment les choisir ? Actes des 11\ieme{} Journées de Méthodologie Statistique, \url{http://jms-insee.fr/jms2012s14_3/}.
\bibitem[Kirchner et al (2018)]{K2018} Kirchner R., Ladiray D. et Mazzi G.L, Quality Measures and Reporting for Seasonal Adjustment, in Handbook on Seasonal Adjustment, edited by G. L. Mazzi, co-edited by D. Ladiray, European Union, Luxembourg. \url{ec.europa.eu/eurostat/web/products-manuals-and-guidelines/-/KS-GQ-18-001}.
\bibitem[Ladiray, Quartier-la-Tente (2018)]{LD2018} Ladiray D. et Quartier-la-Tente A. (2018), « Du bon usage des modèles Reg-ARIMA en désaisonnalisation ». Actes des 13\ieme{} Journées de Méthodologie Statistique, \url{http://jms-insee.fr/jms2018s05_1/}.
\bibitem[Bell (1992)]{B1992} Bell, W. R. (1992), Alternative Approaches to Length of Month Adjustment, Research Report Series 1992-17, Satistical Research Division, U. S. Census Bureau, Washington DC. \url{https://www.census.gov/ts/papers/rr92-17.pdf}.
\end{thebibliography}

### Bibliographie  {.noframenumbering}

\footnotesize

\begin{thebibliography}{999}
\bibitem[Ladiray (2018)]{L2018} Ladiray, D. (2018), Calendar effects, in Handbook on Seasonal Adjustment, edited by G. L. Mazzi, co-edited by D. Ladiray, European Union, Luxembourg. \url{ec.europa.eu/eurostat/web/products-manuals-and-guidelines/-/KS-GQ-18-001}.

\bibitem[Palate (2014)]{P2014} Palate, J. (2014), ‘Calendars in JDemetra+', \url{https://ec.europa.eu/eurostat/cros/content/calendar-regressors-jd_en}.
 
\bibitem[Eurostat (2015)]{E2015} Eurostat (2015), The ESS guidelines for seasonal adjustment, Eurostat manuals and guidelines, Product Code: KS-GQ-15-001. \url{http://ec.europa.eu/eurostat/web/products-manuals-and-guidelines/-/KS-GQ-15-001}.
\end{thebibliography}
